services:
  mysql:
    image: mariadb:12.1
    container_name: instantflow_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
    networks:
      - instantflow_network

  php:
    image: php:8.5-apache
    container_name: instantflow_php
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    networks:
      - instantflow_network
    command: >
      bash -c "
            apt-get update &&
            apt-get install -y unzip git curl &&
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
            cd /var/www/html &&
            composer install &&
            a2enmod rewrite &&
            docker-php-ext-install pdo pdo_mysql &&
            apache2ctl start &&
            tail -f /dev/null
      "

networks:
  instantflow_network:
    driver: bridge